name: Dev Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      profiles: '["dev"]'
      create_release: false
      retention_days: 7
